### ISSUE TITLE
workflows: remove unnecessary github workflow actions

### ISSUE THREAD

**Issue by katilp** [cms-dpoa/cat-hackathon#18]
Keep only the actions that are relevant to the repository.

**Comment by alextintin007** [comment]
Can you push or manually move your workflow work to the main branch?

**Comment by alextintin007** [comment]
I have already deleted all the unnecessary ymls, except the original one you have worked on, you can replace that one

**Comment by alextintin007** [comment]
Should I also delete all the irrelevant workflows done before? There are around 86
